[package]
name = "oki-ml3390"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
humansize = { version = "2.1" }
rusb = { version = "0.9" }
synoptic = { version = "1.2" }
time = { version = "0.3", features = ["formatting", "std"] }
